### ISSUE TITLE
e is not defined

### ISSUE THREAD

**Issue by ericclemmons** [cdonohue/benefit#1]
- `yarn add emotion benefit`
- `import { benefit } from "benefit"

https://codesandbox.io/s/xox10vr4wq

**Comment by ericclemmons** [comment]
Adding `react` fixes it

**Comment by ericclemmons** [comment]
Then I get:
> `ReferenceError: process is not defined[Learn More]`

To reproduce this:

1. cd /tmp
1. npx degit sveltejs/template my-svelte-project
1. cd my-svelte-project
1. yarn add --dev benefit react emotion
1. code .
1. yarn dev

**Comment by cdonohue** [comment]
Hmmm... this might have to do with everything being bundled together. The whole bundle includes the `react` helpers. I'll try having two different entry points for the build.

**Comment by cdonohue** [comment]
This is solved as of https://github.com/cdonohue/benefit/releases/tag/v0.2.10

The imports are split up into 3 entry points:

`benefit`, `benefit/react`, and `benefit/util`
