### ISSUE TITLE
Keep classNames the same?

### ISSUE THREAD

**Issue by ericclemmons** [cdonohue/benefit#10]
When developing, as a utility CSS library, seeing the original classNames (e.g. `m-1`, `rounded`, etc.) when inspecting the output is helpful for validation.

There are some important things to note about this, though:

- Emotion doesn't support this, and has a lot of code around hashing & cashing:

    https://github.com/emotion-js/emotion/blob/014cc50ffb09c02c3af51f26a3f2af15b61b8c33/packages/core/src/jsx.js#L68-L90

- Showing the original classes can "trick" a developer into adding a new class (e.g. `box-shadow`) via DevTools, which wouldn't do _anything_.

- For prototyping, using the raw rules via `class="..."` and injecting `benefit.css` (#8) is the way to go.

- Users of emotion should _expect_ the classNames to be hashed.

- In `development`, we _could_ duplicate them (since they'd be a no-op) just for visibility:

    https://github.com/cdonohue/benefit/blob/master/src/createUtilitiesFromConfig.js#L97

This may be a non-issue, or something to think about at another time.

But I found it somewhat interesting when authoring and then inspecting the HTML and seeing hashed names.

**Comment by cdonohue** [comment]
@ericclemmons I had thought of this before. I think I’d opted for replacing the name with the hash to avoid the confusion (which you point out in #2 above). 

The tough part is that you still want the niceties of emotion, like autoprefixing.

**Comment by cdonohue** [comment]
Maybe the `development` inclusion is the way to go here

**Comment by cdonohue** [comment]
@ericclemmons you still want to go in this direction?

**Comment by ericclemmons** [comment]
I don't feel the pain enough to warrant it. We can revisit with much more use.

**Comment by ericclemmons** [comment]
Now that we've centered around `cx` and `css` behavior, there's a question regarding _how should local development work_?

Some stray observations:

- I personally like starting/prototyping with `tailwind.css` or `benefit.css`, since everything's available with 1 line of HTML.
- I can change `class` **in the browser** and see what I _want_ it to be.
- Without a really fast feedback loop (e.g. HMR, LiveReload, BrowserSync), changing a `class` and then refreshing manually is **cumbersome**.
- When using raw classes, I'm able to quickly search my code for `px-8` and change it.  With computed classes, I can only guess which `<div>` it is I need to change.

What I'd like to have is:

- [ ] The ability to change `class` in the browser & see the changes.
- [ ] Have the "raw" utility classes unchanged in development.

If I were to guess on _how_ to do this:

- When `NODE_ENV === "development"` for the client, _inject all styles/utilities into the page_. Or have a https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver dynamically add the rules as `class` is changed on an element.
- When doing SSR in `development`, either skip computing the class name, or output `class="${computed} ${original}"` so that we don't lose the original `class` arguments.
