### ISSUE TITLE
Use `rollup`

### ISSUE THREAD

**Issue by cdonohue** [cdonohue/benefit#2]
We need a vanilla `benefit` require as well as the ability to require from `benefit/react` as a separate file to get react helpers from.

Example:
```js
import { benefit } from "benefit"
```

_-or-_

```js
import { jsx } from "benefit/react"
```

To support different input/output files, I'm going to experiment with using `rollup` in place of `microbundle`

> https://github.com/rollup/rollup

**Comment by ericclemmons** [comment]
You could do different files (`index.js` vs. `react.js`) which would allow this.

Both will probably export some of the same utilities, but only `benfit/react` would export `jsx`.

**Comment by cdonohue** [comment]
I don't think this is needed any longer now that `microbundle` is bundling multiple entry points 😄
