### ISSUE TITLE
Opt-in to preflight styles

### ISSUE THREAD

**Issue by cdonohue** [cdonohue/benefit#30]
Currently, `preflight` global styles are injected as a sensible default to an app-level styling approach.

This is a bit aggressive and could be more useful if it could be added by the developer.

`benefit`
> named export from package, like `injectPreflight` or similar

`benefit-react`
> `<Preflight />` component

**Comment by ericclemmons** [comment]
Related: https://www.styled-components.com/docs/api#createglobalstyle
